version: '3'
services: 
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - backend
  grbacserver:
    image: grbac-server
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - backend
    depends_on:
      - mongodb

networks:
  backend: 